pipeline {
     agent any

     environment {
          DOCKER_CREDENTIALS_USR = credentials('docker-username')
          DOCKER_CREDENTIALS_PSW = credentials('docker-password')
     }
     
     stages {
          stage('Clone Repository') {
               steps {
                    echo 'Checking out source code...'
                    git branch: 'main', url: 'https://github.com/ibrahimelothmani/5-Essential-DevOps-Mini-Projects.git'
               }
          }
          stage('Docker Build') {
               steps {
                    sh 'docker build -t $DOCKER_CREDENTIALS_USR/$IMAGE_NAME:latest .'
                    sh 'docker login -u $DOCKER_CREDENTIALS_USR -p $DOCKER_CREDENTIALS_PSW'
                    sh 'docker push $DOCKER_CREDENTIALS_USR/$IMAGE_NAME:latest'
               }
          }
          stage('Test') {
               steps {
                    echo 'Testing...'
                    echo 'Tests passed!'
               }
          }
          stage('Deploy') {
          steps {
                    sh 'docker run -d -p 5000:5000 $DOCKER_CREDENTIALS_USR/$IMAGE_NAME:latest'
               }
          }
     }
     
     post {
          success {
               echo 'Pipeline completed successfully!'
          }
          failure {
               echo 'Pipeline failed.'
          }
     }
}